### ISSUE TITLE
Merge exception types

### ISSUE THREAD

**Issue by jeannekamikaze** [SFML-haskell/SFML#15]
I would like to know what you think on this topic.

Currently we have an exception type for every module - MusicException, TextureException, FontException, RectangleShapeException, and the list goes on [1] - and all of them with an identical definition. This seems unnecessary and cumbersome; I can't even remember why we did it this way or if we ever discussed this at all. Do you think it would be sensible to merge all of those exceptions into a single data type, like SFException?

[1] Full list of exceptions:

```
$ grep -R "Exception =" src/
src/SFML/Audio/Music.hs:data MusicException = MusicException String deriving (Show, Typeable)
src/SFML/Audio/SoundBuffer.hs:data SoundBufferException = SoundBufferException String deriving (Show, Typeable)
src/SFML/Audio/SoundBufferRecorder.hs:data SoundBufferRecorderException = SoundBufferRecorderException String deriving (Show, Typeable)
src/SFML/Audio/SoundRecorder.hs:data SoundRecorderException = SoundRecorderException String deriving (Show, Typeable)
src/SFML/Graphics/CircleShape.hs:data CircleShapeException = CircleShapeException String deriving (Show, Typeable)
src/SFML/Graphics/ConvexShape.hs:data ConvexShapeException = ConvexShapeException String deriving (Show, Typeable)
src/SFML/Graphics/Font.hs:data FontException = FontException String deriving (Show, Typeable)
src/SFML/Graphics/Image.hs:data ImageException = ImageException String deriving (Show, Typeable)
src/SFML/Graphics/RectangleShape.hs:data RectangleShapeException = RectangleShapeException String deriving (Show, Typeable)
src/SFML/Graphics/RenderTexture.hs:data RenderTextureException = RenderTextureException String deriving (Show, Typeable)
src/SFML/Graphics/Shader.hs:data ShaderException = ShaderException String deriving (Show, Typeable)
src/SFML/Graphics/Sprite.hs:data SpriteException = SpriteException String deriving (Show, Typeable)
src/SFML/Graphics/Text.hs:data TextException = TextException String deriving (Show, Typeable)
src/SFML/Graphics/Texture.hs:data TextureException = TextureException String deriving (Show, Typeable)
```

**Comment by jeannekamikaze** [comment]
@adinapoli I was waiting for your opinion specifically.

**Comment by adinapoli** [comment]
Hey @jeannekamikaze ,

at glance it sounds good to me. I suspect you did this in the very beginning to keep a 1:1 spirit with SFML, but of course I cannot be sure not being physically present :wink: 

I do agree that the most Haskell-y way of going would be to merge all the exceptions as constructor of a single umbrella type `SFMLException`.

**Comment by jeannekamikaze** [comment]
Yeah, it's weird because neither CSFML or SFML use exceptions; the functions there return false/null on failure. I will merge those exceptions now.

**Comment by adinapoli** [comment]
:+1:

**Comment by jeannekamikaze** [comment]
Closing after pushing change.
