### ISSUE TITLE
SFBounded for Text

### ISSUE THREAD

**Issue by RageYL** [SFML-haskell/SFML#16]
Hi,

Is there any reason why Text is not instance of SFBounded: it has getTextLocalBounds and getTextGlobalBounds ?

If you think it could be relevant to add this instance i can make a pull request.

**Comment by jeannekamikaze** [comment]
Seems like I forgot that instance, Text should indeed be SFBounded. Feel free to make a pull request for this and other changes you may have. Our idea with the bindings is to make them as lower-level as possible without making them too much of a pain to use. SFBounded for instance is not part of the C++ library, but is a type class we made up to mimic C++'s function overloading.

**Comment by jeannekamikaze** [comment]
I'll take care of this one, but feel free to make any other changes, including new type classes or anything that makes the library easier to use.

**Comment by RageYL** [comment]
Thanks for the commit.

If i find anything else i will share my changes ;)
