### ISSUE TITLE
Publish on Hackage

### ISSUE THREAD

**Issue by adinapoli** [SFML-haskell/SFML#2]
(it's Alfredo).

I can do it myself if you don't have an Hackage account :)

A.

**Comment by sulami** [comment]
Hey guys,

I just hit an issue regarding events using the Hackage version. When checking the source, I saw that the Hackage package has not been updated since 2013, resulting in some breakage. It would be really nice if you could upgrade the Hackage package to make it easier to use it with stack.

**Comment by adinapoli** [comment]
Hey,

I think @jeannekamikaze is the man when dealing with `SFML`. Which error are you encountering? I suspect it might be because you are running a very recent `SFML` C++ library installation and possibly this package needs to be updated accordingly?

Also bear in mind you don't need to refer to an uploaded Hackage package if you are using stack. You can refer to a github commit, like this:

```
- location:
    git: git@github.com:SFML-haskell/SFML
    commit: <a_commit_hash>
```

This will make sure `stack` fetches the library from github.

**Comment by sulami** [comment]
On Thu, Nov 05, 2015 at 01:53:43AM -0800, Alfredo Di Napoli wrote:
> Hey,
> 
> I think @jeannekamikaze is the man when dealing with `SFML`. Which error are you encountering? I suspect it might be because you are running a very recent `SFML` C++ library installation and possibly this package needs to be updated accordingly?
> 
Yes, the C++ library is quite recent. The problem is that events have
been added to the event type enum in C++, so most of the events are just
outright broken because because the numbers have shifted. I was already
going ahead to looking at the source and creating a pull request to fix
this, when I saw that here on GitHub, the events have already been
adapted for quite some time, but the Hackage package has never been
updated.

> Also bear in mind you don't need to refer to an uploaded Hackage package if you are using stack. You can refer to a github commit, like this:
> 
> ```
> - location:
>     git: git@github.com:SFML-haskell/SFML
>     commit: <a_commit_hash>
> ```
> 
> This will make sure `stack` fetches the library from github.
> 
I knew this is somehow possible, but did not know the exact syntax,
thanks. But anyways, if the package is on Hackage, I still think it
would be nice if it was current, just so other users are not going
through building it, only to find out later that it is not completely
compatible to the current C++ library. If you want to, I could update it
myself, I would need access to the Hackage package though.

-- 

Robin Schroer

**Comment by jeannekamikaze** [comment]
Would appreciate it if you could deal with Hackage. @adinapoli can you give sulami acccess?

And yes indeed, a recent update in SFML added a few enums to the events and to the blending modes, making the current package on hackage obsolete.

**Comment by adinapoli** [comment]
Sure. @sulami , which is your Hackage username?

**Comment by sulami** [comment]
On Thu, Nov 05, 2015 at 04:53:26AM -0800, Alfredo Di Napoli wrote:
> Sure. @sulami , which is your Hackage username?
> 

It's sulami, just like here.

-- 

Robin Schroer

**Comment by adinapoli** [comment]
Done.

On Thursday, 5 November 2015, Robin Schroer <notifications@github.com>
wrote:
> On Thu, Nov 05, 2015 at 04:53:26AM -0800, Alfredo Di Napoli wrote:
>> Sure. @sulami , which is your Hackage username?
>>
>
> It's sulami, just like here.
>
> --
>
> Robin Schroer
>
> —
> Reply to this email directly or view it on GitHub.<
https://ci5.googleusercontent.com/proxy/-e_k4-WZ0esrqQO8MKmatSwBOpaHRbWV42Au_7667CWtAx_sMSMKaP92MB88nfd596mpkPbqpgx9W1d89VJvkT5xMPpAx_CXU_b1xLi_dtN7bwDZZgO1RYhPGLY0Mn_f9u7kLhkw_kQzjCTADtOlVytzzKFKLA=s0-d-e1-ft#https://github.com/notifications/beacon/AAa-s6QNrBOwfGG2jFHHLLTTxvUjRTnQks5pC01EgaJpZM4BQ_yj.gif
>

**Comment by sulami** [comment]
Okay, I updated the Hackage version, and also bumped the version number to keep it in sync with the SFML C++ library. I maintain a hackage branch [over here](https://github.com/sulami/sfml) with the changes done.

**Comment by adinapoli** [comment]
I think it would be a good idea to merge the branch into upstream/master to
avoid dangling forks.

Let’s see what Marc thinks.

On Thursday, 5 November 2015, Robin Schroer <notifications@github.com>
wrote:
> Okay, I updated the Hackage version, and also bumped the version number
to keep it in sync with the SFML C++ library. I maintain a hackage branch
over here with the changes done.
>
> —
> Reply to this email directly or view it on GitHub.<
https://ci6.googleusercontent.com/proxy/nv4YsZmkd2QKW1hsOc6_EoWVBGTVzhPOtVOJMY-O5ec2yPk0Sem2Woc0cKGF5xFRZ3lNYoMLaZLmPdODmBTD7R4gOaLu6LabndSkQwjiXTIatfnuL0b8lbzpSJxysGuqKP9B8Gzz5NkCf_b3O-30-IOkeE3KPg=s0-d-e1-ft#https://github.com/notifications/beacon/AAa-s-WtFyjPswYsZ3utKOXTJHJSn-bAks5pC1QZgaJpZM4BQ_yj.gif
>

**Comment by jeannekamikaze** [comment]
Yeah, please make pull requests so we can keep everything in here.
