### ISSUE TITLE
Generate haddock docs

### ISSUE THREAD

**Issue by adinapoli** [SFML-haskell/SFML#7]
That will help people understanding the API.
Apparently for Hackage to generate the docs periodically we need to first upload the package after invoking "cabal haddock"

**Comment by ppelleti** [comment]
As a stopgap measure, I've uploaded the haddock docs to [my website][1].  Feel free to browse them there.  It would be nice to have the docs on Hackage, though.

[1]: http://funwithsoftware.org/haddock/SFML-2.3.2.2/

**Comment by ppelleti** [comment]
I just used `cabal upload --documentation` for one of my own packages, and it worked like a charm.  (I believe this requires cabal 1.24 or higher, though.)

If you prefer, I'd be happy to upload the SFML docs to Hackage for you, if you add me to the maintainer group for SFML on Hackage.  (My Hackage username is "ppelleti".)

**Comment by jeannekamikaze** [comment]
@adinapoli, can you give @ppelleti access?

**Comment by adinapoli** [comment]
@ppelleti @jeannekamikaze I have added the user on the Maintainers group on Hackage, but it's not showing up for some reason!

Patrick, would you give a go and report back? It might simply be it will take a while for the user to show up...

**Comment by ppelleti** [comment]
@adinapoli I'm showing up on the maintainer list now, and I was able to successfully execute `cabal upload --documentation` for 2.3.2.4.  After a brief delay, the docs appeared on Hackage.

I went ahead and repeated the process for the older versions, too.  The docs are now showing up for all of them, as well.  So I think we're in good shape.

**Comment by jeannekamikaze** [comment]
Docs are looking great, thanks @ppelleti.

**Comment by adinapoli** [comment]
Thanks @ppelleti !

**Comment by jeannekamikaze** [comment]
Closing since docs have been uploaded.
